# Generated by Django 4.1.7 on 2023-02-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='search', max_length=200)),
                ('type', models.TextField(choices=[('ai', 'ai'), ('search', 'search')], default='search')),
                ('series', models.JSONField(default=dict)),
                ('redirect', models.CharField(default='/analytic', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='chart', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('series', models.JSONField()),
                ('type', models.TextField(default='line')),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['company_id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Пользователь', max_length=200)),
                ('company_name', models.CharField(default='company', max_length=200)),
                ('avatar', models.TextField()),
                ('role', models.TextField(choices=[('director', 'Директор'), ('top-manager', 'Топ-менеджер'), ('manager', 'Менеджер')], default='manager')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
