# Generated by Django 4.1.7 on 2023-02-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
