# Generated by Django 4.1.7 on 2023-02-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
