# Generated by Django 4.1.7 on 2023-02-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_owners_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(auto_created=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['company_id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(auto_created=True)),
                ('user_name', models.CharField(default='Пользователь', max_length=200)),
                ('user_role', models.CharField(default='user', max_length=100)),
                ('user_photo', models.ImageField(upload_to='')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.DeleteModel(
            name='Owners',
        ),
    ]
