# Generated by Django 4.1.7 on 2023-02-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_companies_id_remove_users_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_role',
            field=models.TextField(choices=[('director', 'Директор'), ('top-manager', 'Топ-менеджер'), ('manager', 'Менеджер')], default='manager'),
        ),
    ]
