# Generated by Django 4.1.7 on 2023-02-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_users_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_photo',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_role',
            new_name='role',
        ),
    ]
