# Generated by Django 4.1.7 on 2023-02-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_users_options_rename_user_photo_users_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.TextField(),
        ),
    ]
