# Generated by Django 4.1.7 on 2023-02-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='company_name',
            field=models.CharField(default='company', max_length=200),
        ),
    ]
