# Generated by Django 4.1.7 on 2023-02-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_analytic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytic',
            old_name='expenses',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='analytic',
            old_name='data',
            new_name='series',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='income',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='revenue',
        ),
        migrations.AddField(
            model_name='analytic',
            name='name',
            field=models.CharField(default='chart', max_length=200),
        ),
    ]
