# Generated by Django 4.1.7 on 2023-02-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_analytic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='search', max_length=200)),
                ('type', models.TextField(choices=[('ai', 'ai'), ('search', 'search')], default='search')),
                ('redirect', models.TextField()),
            ],
        ),
    ]
