# Generated by Django 4.1.7 on 2023-02-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_action_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='series',
            field=models.JSONField(default=dict),
        ),
    ]
