# Generated by Django 4.1.7 on 2023-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_action_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='redirect',
            field=models.CharField(default='/analytic', max_length=200),
        ),
    ]
