# Generated by Django 4.1.7 on 2023-02-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_action_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='series',
            field=models.JSONField(),
        ),
    ]
